# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: jasisz blog
email: jasisz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Ten blog z pewnością cię nie śledzi i nie używa ciasteczek.<br/>
    To dobry, grzeczny blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jasisz.github.io" # the base hostname & protocol for your site
twitter_username: jasisz1
github_username:  jasisz

# Build settings
markdown: kramdown

permalink: /:title
