# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Czary mary
email: jasisz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Ot taki blog, na którym będzie
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jasisz.github.io" # the base hostname & protocol for your site
twitter_username: jasisz1
github_username:  jasisz

# Build settings
markdown: kramdown
